FROM oven/bun:latest AS base

ENV NODE_ENV=development

WORKDIR /app

# Build
FROM base AS build

COPY --link package.json bun.lock .
RUN bun i

# Run
FROM base

COPY --from=build /app/node_modules /app/node_modules

CMD [ "bun", "dev" ]
